<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<link rel="stylesheet" href="css/style.css" type="text/css">
<body>
<table>
    <tr>
        <th>
            <a href="index.php?data=set" id="start">URI maken</a>
        </th>
        <td>
            <div class="form">
                <form action="Base64Encode.php" method="post" enctype="multipart/form-data">
                    <a id="link" href="index.php?data=get&download=false">bestand openen?</a>
                    <input type="hidden" name="MAX_FILE_SIZE" value="2000000">
                    <?php
                    if (isset($_SESSION['message'])) {
                        echo get_message();
                        if ($_GET['download'] === 'true') {
                            echo "<div><a href=\"http://localhost/file-to-string/images/{$_SESSION['file_name']}\" id=\"button\" download>Opslaan</a><span id=\"file_name\">{$_SESSION['file_name']}</span></div>";
                        }
                    } else {
                        ?>
                        <input type="file" id="file" name="file">
                        <input id="set_submit_link" type="submit" name="submit" value="base64">
                        <?php
                    }
                    ?>
                </form>
            </div>
        </td>
    </tr>
</table>
</body>
</html>